Codruta:
  dailySalesBonus: 200.0
  firstLastHourBonus: 0.0
  socialMediaBonus: 0.0
  managementBonus: 0.0
  managementConsistencyBonus: 0.0
  transportFuel: 0.0
  personalSalesBonus: 0.0
  extraBonus: 0.0
  dailyAllowance: 0.0
  manualHours: 0.0
  deductions: 0.0
  rent: 0.0
  advance: 0.0
